### PR TITLE
Add sample for custom `editorUrl` prop

### LINKED ISSUE #235: Add sample for `editorUrl`
## Are you reporting a feature request or a bug?

Feature request

## Provide detailed reproduction steps (if any)

Integration v2 is missing a sample usage of custom `editorUrl`.

Related issue: #234

### PR DESCRIPTION
**Pull request by MMMalik**
This PR adds a sample for custom `editorUrl` prop. A latest standard version of CKEditor 4 was downloaded from [here](https://ckeditor.com/ckeditor-4/download/).

To test, run `editor-url` sample.

Closes #235.

### CODE REVIEW

**Review by f1ames — CHANGES_REQUESTED** [review]
I wonder if we really want to include all CKEditor 4 files here, especially that:

*   If we have it, it will be good to update it regularly which may be cumbersome.
*   If samples are part of the production package (not sure TBH, @MMMalik?) it will increase the package size a lot.

Maybe we could add `ckeditor4` package as a NPM dependency and build step could move all necessary files to `ckeditor` folder? Not sure how well it could work with forking samples via CodeSandbox :thinking:

**Comment by MMMalik** [comment]
> If samples are part of the production package (not sure TBH, @MMMalik?) it will increase the package size a lot.

They are not 😄.

> Maybe we could add ckeditor4 package as a NPM dependency and build step could move all necessary files to ckeditor folder?

That's a better idea. I'll improve that.

**Comment by MMMalik** [comment]
Hi @f1ames,

I've merged latest `major` into `t/234` and moved `ckeditor4` to listed dependencies.

**Comment by f1ames** [comment]
Rebased onto latest `major`.

**Review by f1ames — APPROVED** [review]
LGTM :+1:

**Pull request merged**
