### PR TITLE
Enable official support for React 18

### LINKED ISSUE #284: Ensure that package works correctly with React 18
## Are you reporting a feature request or a bug?

Other

## Provide detailed reproduction steps (if any)

A new major version of React that has been recently released.

https://reactjs.org/blog/2022/03/29/react-v18.html
https://github.com/facebook/react/releases/tag/v18.0.0

Ensure that `ckeditor4-react` works fine with React 18. Adjust testing scenarios so that they include React 18 as well.

### PR DESCRIPTION
**Pull request by MMMalik**
This PR officially enables support for React 18. The following work has been done:
- React 18 is now supported via `peerDependencies` field in `package.json`.
- Unit tests are adjusted according to new API of [React Testing Library].(https://testing-library.com/docs/react-testing-library/intro/), especially with regards to [React Hooks](https://github.com/testing-library/react-hooks-testing-library#a-note-about-react-18-support)
- Slight updates to karma config.
- Dependencies are upgraded, if possible (one exception is e.g. `chalk` which relies on ESM since v5).
- TypeScript version range is now limited to patch updates (TS doesn't follow semantic versioning).

Closes #284.

### CODE REVIEW

**Comment by MMMalik** [comment]
This is ready for review.

One more considration to be taken into account: React 18 drops support for IE11 :see_no_evil:. So if we enable support for React 18 exclusively, then we also basically drop support for IE11 in React integration.

---

There are still alternative routes we can take. For instance, we can enable support for React from 16.8.x to 18.x AND loosen our testing policies:
- Run full suite of unit tests for React 18.x and E2E tests for selected versions from 16.8.x to 18.x
- OR: Run full suite of unit tests for selected versions from 16.8.x to 17.x and E2E tests for selected versions from 16.8.x to 18.x

This way we could cover with tests all versions our source code would work on and unlock official support for React 16.8 to 18.x via `peerDependencies`:

```json
"peerDependencies": {
	"ckeditor4": "^4.19.0",
	"react": "^16.8 || ^17 || ^18"
},
```

**Review by Comandeer — CHANGES_REQUESTED** [review]
The code looks good and all samples work correctly.

However, I have issue when running tests locally. I've run `npm t` and it failed during linting:

```
/Users/comandeer/repos/ckeditor4/ckeditor4-react/src/events.ts
  6:1  error  All imports in the declaration are only used as types. Use `import type`  @typescript-eslint/consistent-type-imports

/Users/comandeer/repos/ckeditor4/ckeditor4-react/src/registerEditorEventHandler.ts
  8:1  error  All imports in the declaration are only used as types. Use `import type`  @typescript-eslint/consistent-type-imports

/Users/comandeer/repos/ckeditor4/ckeditor4-react/src/types.ts
   6:1   error  All imports in the declaration are only used as types. Use `import type`  @typescript-eslint/consistent-type-imports
   7:1   error  All imports in the declaration are only used as types. Use `import type`  @typescript-eslint/consistent-type-imports
   8:1   error  All imports in the declaration are only used as types. Use `import type`  @typescript-eslint/consistent-type-imports
   9:1   error  All imports in the declaration are only used as types. Use `import type`  @typescript-eslint/consistent-type-imports
  61:17  error  void is only valid as a return type or generic type variable              @typescript-eslint/no-invalid-void-type
  66:25  error  void is only valid as a return type or generic type variable              @typescript-eslint/no-invalid-void-type
  71:15  error  void is only valid as a return type or generic type variable              @typescript-eslint/no-invalid-void-type

/Users/comandeer/repos/ckeditor4/ckeditor4-react/src/useCKEditor.ts
  16:1  error  All imports in the declaration are only used as types. Use `import type`  @typescript-eslint/consistent-type-imports

/Users/comandeer/repos/ckeditor4/ckeditor4-react/src/utils.ts
  6:1  error  All imports in the declaration are only used as types. Use `import type`  @typescript-eslint/consistent-type-imports
  7:1  error  All imports in the declaration are only used as types. Use `import type`  @typescript-eslint/consistent-type-imports

✖ 12 problems (12 errors, 0 warnings)
  9 errors and 0 warnings potentially fixable with the `--fix` option.
```

Could you look into it?

**Review by Comandeer — CHANGES_REQUESTED** [review]
Seems to work well, but there is an error connected with samples:

```
Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
```

Could you take a look at it?

**Comment by MMMalik** [comment]
- As discussed on Slack, old link to documentation is brought back.
- Samples are adjusted to use new `react-dom/client` API.
- Polyfills for IE11 are removed from samples.

**Review by Comandeer — APPROVED** [review]
LGTM!

**Pull request merged**
