### PR TITLE
Provide code samples for easier issue reporting

### PR DESCRIPTION
**Pull request by KarolDawidziuk**
I've provide code samples from `CodeSandbox` and `StackBlitz` for easier issue reporting.

Closes [#170](https://github.com/ckeditor/ckeditor4-react/issues/170).

### CODE REVIEW

**Comment by MMMalik** [comment]
Hi @KarolDawidziuk,

the samples you provided look fine to me. However, the new major version of React will provide standalone samples as part of the repository. We might want to put this PR on hold for a while and wait for a stable release of `ckeditor-react` `2.0.0`.

**Comment by f1ames** [comment]
> However, the new major version of React will provide standalone samples as part of the repository. We might want to put this PR on hold for a while and wait for a stable release of `ckeditor-react` `2.0.0`.

Good point @MMMalik :+1: Since we will have both versions in this repo (and I expect there will be some issues reported to 1.x.x versions too), maybe we could adjust the template to say, something like "For v1.x.x use those samples and for 2.x.x use fork those provided in the repo"?

**Comment by MMMalik** [comment]
Yeah, I think that's a good idea.

**Review by Dumluregn — CHANGES_REQUESTED** [review]
Looks good, only one thing to fix - in StackBlitz sample you can't change dependency version through a dropdown (AFAICS it has to be done in `package.json` file). Please adjust this part of description and we are good to go - and after v2 release when adding the new samples to issue template we'll need a note mentioned in https://github.com/ckeditor/ckeditor4-react/pull/218#issuecomment-864882954.

**Comment by KarolDawidziuk** [comment]
Thanks guys for the review!

I've added information about fork v2 with supplied samples to bug report and also updated information about changing version in StackBlitz.

**Review by Dumluregn — APPROVED** [review]
LGTM 🎉

**Pull request merged**
