### PR TITLE
Revert sinon update

### LINKED ISSUE #206: IE11 tests fail due to sinon update
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

Run tests on IE11 via Browserstack.

### Expected result

Tests pass

### Actual result

Tests fail due to:

image

https://github.com/ckeditor/ckeditor4-react/runs/2509827429?check_suite_focus=true

This might be the result of recent update of `sinon` to v10.

### PR DESCRIPTION
**Pull request by MMMalik**
The following has been accomplished within this PR:

1. `sinon` has been downgraded in order to make tests on IE11 great again.
2. `check-pr` workflow has been deleted in favor of `test-all` workflow. The latter will now handle PRs as well. It looks like we should run tests on all browsers for all PRs after all...

Closes #206.

### CODE REVIEW

**Review by f1ames — CHANGES_REQUESTED** [review]
> 1.  `sinon` has been downgraded in order to make tests on IE11 great again.

You mean to make tests on IE11 **green** again? :smile: 

> 2\. `check-pr` workflow has been deleted in favor of `test-all` workflow. The latter will now handle PRs as well. It looks like we should run tests on all browsers for all PRs after all...

Makes sense, but from what I see it now runs tests on all browsers with all React versions (all we test on `master` too). Maybe for PRs we can test on all browsers but with latest React version only? I guess it can be determined by checking some [default env variables](https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables). WDYT?

**Comment by MMMalik** [comment]
> You mean to make tests on IE11 **green** again? 😄

Exactly, that was a spelling mistake.

> Maybe for PRs we can test on all browsers but with latest React version only?

That makes sense, I made a small adjustment by leveraging `GITHUB_HEAD_REF` variable (only set for pull request events).

Please check now.

**Comment by f1ames** [comment]
Rebased onto latest `master`.

**Review by f1ames — APPROVED** [review]
> That makes sense, I made a small adjustment by leveraging `GITHUB_HEAD_REF` variable (only set for pull request events).

LGTM :+1:

**Pull request merged**
