### PR TITLE
fix: upgrade React min version to 16.9

### LINKED ISSUE #221: Test command for testing all versions skips 16.8.* version
## Are you reporting a feature request or a bug?

Task

## Provide detailed reproduction steps (if any)

While running `npm run test:units:all` it runs tests for following versions:

image

Since we support React version starting form `16.8.3` as mentioned in `package.json` `16.8.*` version should be tested too.

### PR DESCRIPTION
**Pull request by MMMalik**
Upgrades min version of React inside `peerDependencies` to `^16.9`. Also, `package-lock.json` files inside samples were updated.

Closes #221.

### CODE REVIEW

**Review by f1ames — CHANGES_REQUESTED** [review]
Generally looks good :+1: 

One question though, I see samples use our package version from NPM (so we have `2.0.0-rc.1` there and `ckeditor4-integrations-common` version `0.2.0` ). Have you considered what would be pros/cons of using local build (or giving an ability to use it)?

**Comment by MMMalik** [comment]
Local build can be used with help of `npm link` command. It's described in details in CONTRIBUTING file [here](https://github.com/ckeditor/ckeditor4-react/blob/major/CONTRIBUTING.md#samples).

Regarding versions in lock files inside `samples`, we might need to regenerate those files anytime a new version of `ckeditor4-react` is published. This can be automated, so I can add a follow-up task. It's not mandatory though, because we use `latest` version of `ckeditor4-react` inside `package.json` anyway.

**Review by f1ames — APPROVED** [review]
> Local build can be used with help of `npm link` command. It's described in details in CONTRIBUTING file [here](https://github.com/ckeditor/ckeditor4-react/blob/major/CONTRIBUTING.md#samples).

:+1: 

> Regarding versions in lock files inside `samples`, we might need to regenerate those files anytime a new version of `ckeditor4-react` is published. This can be automated, so I can add a follow-up task. It's not mandatory though, because we use `latest` version of `ckeditor4-react` inside `package.json` anyway.

Ok, makes sense, let's leave it as is then :+1:

**Comment by f1ames** [comment]
Rebased onto latest `major`.

**Pull request merged**
